env:
  global:
    - CC_TEST_REPORTER_ID=0078f4bf92a5a525bb5b3af4a2d3c6b8ba516a00c1a01c52638b5fc80a181484
    - SCALA_VERSION=2.12
language: scala

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - sbt clean coverage test coverageReport
after_script:
  - ./cc-test-reporter format-coverage -t cobertura target/scala-${SCALA_VERSION}/coverage-report/cobertura.xml -o result/typed.json
  - ./cc-test-reporter format-coverage -t cobertura typedsl/target/scala-${SCALA_VERSION}/coverage-report/cobertura.xml  -o result/typedsl.json
  - ./cc-test-reporter format-coverage -t cobertura macros/target/scala-${SCALA_VERSION}/coverage-report/cobertura.xml  -o result/macros.json
  - ./cc-test-reporter sum-coverage result/*.json -p 3
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
